name: miniscriptgen
description: A code generator for Miniscript.
version: 0.0.1-alpha6
repository: https://github.com/dartleaf/miniscript.gen

environment:
  sdk: ^3.7.2

# Add regular dependencies here.
dependencies:
  miniscript: ^1.6.2-10
  source_gen: ^1.4.0
  build: ^2.4.0
  analyzer: ^6.11.0
  miniscriptgenlib: ^0.0.1-alpha6
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
  build_runner: ^2.4.0
